default_job = "clippy"

[jobs.clippy]
command = ["cargo", "clippy", "--", "-D", "warnings"]
on_success = "job:test"

[jobs.test]
command = ["cargo", "test"]
on_success = "job:run"

[jobs.run]
command = ["cargo", "run"]
